### ISSUE TITLE
Cannot set path when creating new Neo Express instance

### ISSUE THREAD

**Issue by csmuller** [neo-project/neo-visual-tracker#135]
When trying to create a new Neo Express instance via the menu "Create new Neo Express instance", I can't set the configuration path to anything else than the root path (which is set by default). The creation then fails, probably because it fail to write to root.

<img width="374" alt="Screenshot 2020-06-16 at 10 07 51" src="https://user-images.githubusercontent.com/37138571/84749534-60247000-afba-11ea-9584-297c576522a4.png">

Neo Blockchain Toolkit: `1.1.11`
VSCode: 
```
Version: 1.46.0
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0
```

**Comment by djnicholson** [comment]
Under the hood, this uses a <input type="file" webkitdirectory /> element. The webkitdirectory attribute allows the user to pick a folder instead of a file. Once the user has picked a folder, the browser recurses within that folder and creates an array with one element for every file.  We throw that array away (we only care what the top-level folder was) but cannot avoid it being created.

@csmuller for a workaround, try selecting a folder with less children (e.g. an empty directory). I believe that will work but it would be great if you can confirm.

I'll investigate a proper fix.  I think we'll need to defer folder selection to the extension code running in the context of VSCode, not the web browser panel.

**Comment by djnicholson** [comment]
Note to self: Folder selection when creating a checkpoint has the same issue.

**Comment by csmuller** [comment]
@djnicholson, Choosing a completely empty folder didn't work. In this case, the path is simply not changed but no error appears in the console of the dev tools.

Anyway, I was able to run a node when i opened a folder in the VSCode workspace. That folder then serves as the root folder when creating a neo express instance.

**Comment by djnicholson** [comment]
Not quite sure why selecting an empty folder was not working for you, @csmuller.  Regardless, I have made a change to how we do the folder selection anyway (because performance was terrible even when it did work).  The code is now in master and their is a build of the VSIX [here](https://dev.azure.com/NGDSeattle/Public/_build/results?buildId=784&view=artifacts&type=publishedArtifacts) if you would like to test it.
